# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-17.10"
  config.vm.network "forwarded_port", guest: 3000, host: 8080, host_ip: "127.0.0.1"

  config.vm.provision "shell", inline: <<-SHELL
    # Initialise
    sudo apt-get -qq update
    sudo apt-get install -qq git build-essential
    
    # Install Node.js
    curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    sudo apt-get install -y nodejs

    # Install MongoDB
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
    echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
    sudo apt -qq update && sudo apt install -y mongodb-org

    # MongoDB -- Start and verify
    sudo service mongod start
    sudo service mongod status    

    # Finalise
    echo "MongoDB installed but not configured!"
  SHELL
end
